### ISSUE TITLE
what software/app you using for fan, temperature, sensor,,etc control ?

### ISSUE THREAD

**Issue by SimbahJohn** [sqlsec/MSI-MAG-B560M-MORTAR-i7-10700#11]
I finished my hac, b560m mortar non wifi, monterey 12.6 smoothly, thank for your hac reference as base, and now using 0.8.5 opencore, i just wanna ask, what app you are using for that cute information bar, thank you

**Comment by sqlsec** [comment]
@SimbahJohn  [https://lemon.qq.com/](https://lemon.qq.com/) 畅快清理 · 全新体验
“腾讯柠檬清理”正式发布！匠心打磨清理体验，一键释放磁盘空间
