### ISSUE TITLE
麦克风输入无效，有解吗？

### ISSUE THREAD

**Issue by bits1125** [sqlsec/MSI-MAG-B560M-MORTAR-i7-10700#2]
大佬，配置相近，i9-10900k+微星B560迫击炮Wi-Fi+盈通RX560D，发现两个问题，其一是麦克风输入无效，其二是开机速度明显比我之前b460慢，不知何故。
还有就是，我USB完整定制了，包含type-c，需要的话可以发你。itlwm驱动已经可以支持AX210了，我昨天试了，无线网卡可以正常连接，速度没测试，蓝牙无法使用。

**Comment by sqlsec** [comment]
1. 麦克风输入无效这个我确实没有解决，因为只找到了 alcid 有声音就行了，我推荐室友如果要用的话 用 USB 麦克风的，我自己的 Z490 的麦克风也无效，我使用的也是 USB 麦克风。
2. 开机速度慢应该是卡核显了，可以尝试把 显卡注入的 id 值改为仅计算使用看看，这样应该会快一点，当时为了截图做视频，所以把核显也单独注入了。
3. 欢迎共享你制作的 usbport.txt 可以发我邮箱 admin@sqlsec.com
4. 这个 itlwm驱动已经可以支持AX210 确实是在我文章发布后不久支持的，我过段时间在这个项目也更新一下
