### ISSUE TITLE
我也对这套配置有意，能帮忙测一下Firefox下4K视频解码正常吗？

### ISSUE THREAD

**Issue by wonpn** [sqlsec/MSI-MAG-B560M-MORTAR-i7-10700#4]
我原来的cpu 是6500，无论核显UHD530 还是 RX 570 ，firefox解码始终不行，4k视频卡成ppt。
您有空可以帮试一下吗

**Comment by sqlsec** [comment]
理论上应该不卡的吧，这个是我大学室友的配置 我帮他远程配置的 我没法上手测试 后续这个驱动我也不方便维护更新了
