### ISSUE TITLE
我现在和你配置一样的 也安装上了 其他功能正常 可是没有vda, intel 630不能识别出来

### ISSUE THREAD

**Issue by MrFar20** [sqlsec/MSI-MAG-B560M-MORTAR-i7-10700#5]
<img width="361" alt="截屏2021-08-28 下午10 45 07" src="https://user-images.githubusercontent.com/31307737/131221822-2d1555ee-a36c-4c9a-be68-245f4d8e0deb.png">

**Comment by sqlsec** [comment]
检查一下 是不是 SMBIOS设置的不对 理论上是可以直接启动的

**Comment by MrFar20** [comment]
可以了 我主办核显没开

**Comment by MrFar20** [comment]
现在我重新定制了usb, 定制后定制的端口正常使用, 但是hacintool里面识别不到usb 睡眠也正常
