### ISSUE TITLE
安装时读条到一半直接黑屏

### ISSUE THREAD

**Issue by IITII** [sqlsec/MSI-MAG-B560M-MORTAR-i7-10700#7]
```
* i5-10600k
* 16Gx2 3200MHz 海盗船
* MSI 560M-mortar
* UHD 630
* 无独显
```

* 没有独显，只有集显
* bios里面 PEG，IGD都试过，一样的结果
* 已修改 UUID，MLB等，基于 iMac19,1 生成

使用 BigSur11.4 启动盘进行引导，EFI分区的EFI文件夹使用 DiskGenius 进行替换的，BIOS CFG 已关闭（SGX没找到）。

可以正常进入系统选择菜单，选择启动盘之后，进入读条，读条到一半，屏幕黑屏，但是风扇一直在工作，直接按开机键也不会立即关机，感觉上像是正常开机了。

* 是不是哪里设置错了，没有开启集显输出？

> 感谢您的时间和帮助  ：-）

**Comment by IITII** [comment]
bios 里面使用 IGD 输出，尝试添加 HDMI20 依旧无效，读条到一半黑屏，但是感觉上电脑还在运行

```xml
<key>enable-hdmi20</key>
<data>AQAAAA==</data>
```

**Comment by sqlsec** [comment]
正常的，目前这主板不支持核显输出，买个免驱的独显就OK了

**Comment by sqlsec** [comment]
这个我B站的视频也提到过这个点，之前没有独显的时候也一直黑屏，但是并不是网上说的无解，搞个免驱卡进去 会发现核显依然可以正常工作的。推荐 蓝宝石 RX460

**Comment by IITII** [comment]
emmm，好吧。

README里面以及Release并没有提及相关信息，也没有B站的视频链接，踩坑了。。。

**Comment by IITII** [comment]
那这个不支持核显输出是哪的限制呢？BIOS还是主板，还是黑苹果，windows下面好像可以正常输出。

**Comment by sqlsec** [comment]
Realease 里面写了我博客文章，博客文章里面写了视频地址，而且博客文章里面也提到了无法输出。不过确实 README.md 漏了，我刚刚补上了

**Comment by sqlsec** [comment]
黑苹果的限制，因为B560M 理论上应该搭配11代CPU使用的，但是11代CPU的核显和10代核显变化很大，导致黑苹果这块并无法驱动
