### ISSUE TITLE
Can not headless iGPU with MAG B560m Mortar non Wifi?

### ISSUE THREAD

**Issue by acedance** [sqlsec/MSI-MAG-B560M-MORTAR-i7-10700#8]
Hi! Can you use headless iGPU for this mainboard with i7 10700? I can't use headless, VDA encoder fails with 0300C89B.

I don't know why my Graphics only show RX 470 (I use the code iGPU drive a display to get VDA encoder enable) and your dual card shows.

My spec same as you:
- i7 10700.
- MAG MSI B560M Mortar non wifi.
- AMD rx 470.
- Smbios 20,1.
- Mac OS 11.6.
- OC: 0.7.2.

<img width="938" alt="Screen Shot 2021-10-04 at 14 03 48" src="https://user-images.githubusercontent.com/24824881/135807623-3babe42b-1cbd-4d51-af03-f35f08be01b6.png">

**Comment by haipham22** [comment]
same issue

**Comment by sqlsec** [comment]
@haipham22 @acedance detail in my article: [台式机双显卡显示](https://apple.sqlsec.com/6-%E5%AE%9E%E7%94%A8%E5%A7%BF%E5%8A%BF/6-4.html)
